version: "2"

services:

  zendserver:
    image: janatzend/zend-server:9.1ea-php7.1-apache
    #image: janatzend/zend-server:9.1ea-php7.1-nginx
    ports:
      - 8090:80
      - 8091:10081
    environment:
      - APACHE_ULIMIT_MAX_FILES="ulimit -n 4096"
      - TCP_PORTS=80, 10081
      - BALANCE=source
      - EXCLUDE_PORTS=443,10082
    volumes:
      - /webapi
      - .:/usr/local/zend/var/plugins/sunbursttrace
    links:
      - 'mysql:DB'

  mysql:
    image: 'mysql:5.6'
    ports:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'ZendServer'
